### ISSUE TITLE
打扰您了，求解

### ISSUE THREAD

**Issue by vr1yan** [hou6663/hou6663.github.io#1]
.

**Comment by ACSDSZ** [comment]
> 请问apple究竟是什么，😭可否给个提示，已经把文件内的翻遍了

可以说一下吗找半天了 实在没有头绪

**Comment by xieshicheng112** [comment]
你好,我也找了很久了,没有头绪,是否是个网址

**Comment by hou6663** [comment]
还没找到吗，确实是个网址

**Comment by hou6663** [comment]
只不过这个网址不是我们平常的网址，是一个需要识别的网址，也就在色图里面

**Comment by xieshicheng112** [comment]
> 找到了鸡屁股，方向是不是错了

加油,你已经很接近了

**Comment by WalkerZe** [comment]
> > 找到了鸡屁股，方向是不是错了
> 
> 加油,你已经很接近了

还有什么提示吗，卡了好久了，孩子麻了

**Comment by xieshicheng112** [comment]
> > > 找到了鸡屁股，方向是不是错了
> > 
> > 
> > 加油,你已经很接近了
> 
> 还有什么提示吗，卡了好久了，孩子麻了

要仔细,be Carefully!有时候真相就在你的眼前

**Comment by WalkerZe** [comment]
> > > > 找到了鸡屁股，方向是不是错了
> > > 
> > > 
> > > 加油,你已经很接近了
> > 
> > 
> > 还有什么提示吗，卡了好久了，孩子麻了
> 
> 要仔细,be Carefully!有时候真相就在你的眼前

我现在单纯就是想解开这个谜题了，但是一直找不到，眼瞎了，可以邮件沟通吗，谢谢。
xavierlee_79@outlook.com
